architecture: replicaset
replicaCount: 3

auth:
  enabled: true
  rootUser: admin
  rootPassword: adminPassword
  username: appuser
  password: appuserPassword
  database: eletricity_usage

image:
  repository: bitnami/mongodb
  tag: 7.0.5-debian-11-r13
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePorts:
    mongodb: 32017
  port: 27017

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

extraFlags:
  - "--bind_ip_all"

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

ingress:
  enabled: false

autoscaling:
  enabled: false
