architecture: replicaset

replicaCount: 3

auth:
  enabled: true
  rootUser: admin
  rootPassword: adminPassword
  username: appuser
  password: appuserPassword
  database: eletricity_usage

service:
  type: NodePort
  nodePorts:
    mongodb: 32017
  port: 27017

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

extraFlags:
  - "--bind_ip_all"

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

ingress:
  enabled: false  # ğŸ‘ˆ è§£æ±ºä½ ç›®å‰çš„ crash å•é¡Œ
